### ISSUE TITLE
exception on "* with debugger" commands in AS Chipmunk | 2021.2.1

### ISSUE THREAD

**Issue by thegeekbird** [pbreault/adb-idea#144]
Attempt to "restart with debugger" for example produces exception

`org.joor.ReflectException: java.lang.NoSuchMethodException: No similar method attachToClient with params [class com.intellij.openapi.project.impl.ProjectExImpl, class com.android.ddmlib.internal.ClientImpl] could be found on type class com.android.tools.idea.run.editor.AndroidJavaDebugger.
	at org.joor.Reflect.call(Reflect.java:585)
	at com.developerphil.adbidea.debugger.AttachToClient.getPreviousImplementation(Debugger.kt:91)
	at com.developerphil.adbidea.debugger.AttachToClient.getPreviousImplementation(Debugger.kt:83)
	at com.developerphil.adbidea.compatibility.BackwardCompatibleGetter.get(BackwardCompatibleGetter.kt:13)
	at com.developerphil.adbidea.debugger.Debugger.closeOldSessionAndRun(Debugger.kt:35)
	at com.developerphil.adbidea.debugger.Debugger.access$closeOldSessionAndRun(Debugger.kt:17)
	at com.developerphil.adbidea.debugger.Debugger$attach$2.invoke(Debugger.kt:27)
	at com.developerphil.adbidea.debugger.Debugger$attach$2.invoke(Debugger.kt:27)
	at com.developerphil.adbidea.HelperMethodsKt.invokeLater$lambda-0(HelperMethods.kt:16)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:486)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.NoSuchMethodException: No similar method attachToClient with params [class com.intellij.openapi.project.impl.ProjectExImpl, class com.android.ddmlib.internal.ClientImpl] could be found on type class com.android.tools.idea.run.editor.AndroidJavaDebugger.
	at org.joor.Reflect.similarMethod(Reflect.java:652)
	at org.joor.Reflect.call(Reflect.java:582)
	... 37 more
`

in IDE and app on device hangs "waiting for debugger". Introduced after IDE update.

Env:
Android Studio Chipmunk | 2021.2.1 Patch 2
Build #AI-212.5712.43.2112.8815526, built on July 10, 2022
com.developerphil.adbidea (1.6.5 & 1.6.6)

**Comment by soenkegissel** [comment]
Any news on this issue?

**Comment by pbreault** [comment]
Thanks for the report. I'm able to reproduce the issue. Should have a a fix soon.

**Comment by pbreault** [comment]
Fixed in 1.6.7 for chipmunk and 1.6.8 for dolphin+.
