### ISSUE TITLE
Android Studio 1.4

### ISSUE THREAD

**Issue by xgear-public** [pbreault/adb-idea#25]
When few devices connected after choosing command get exception:

java.lang.NoSuchMethodException: org.jetbrains.android.run.DeviceChooser.<init>(java.lang.Boolean, com.intellij.openapi.ui.DialogWrapper$OkAction, org.jetbrains.android.facet.AndroidFacet, com.developerphil.adbidea.ui.DeviceChooserDialog$2)
org.joor.ReflectException: java.lang.NoSuchMethodException: org.jetbrains.android.run.DeviceChooser.<init>(java.lang.Boolean, com.intellij.openapi.ui.DialogWrapper$OkAction, org.jetbrains.android.facet.AndroidFacet, com.developerphil.adbidea.ui.DeviceChooserDialog$2)
	at org.joor.Reflect.create(Reflect.java:422)
	at com.developerphil.adbidea.ui.DeviceChooserDialog.buildPreZeroDotSixDeviceChooser(DeviceChooserDialog.java:75)
	at com.developerphil.adbidea.ui.DeviceChooserDialog.newDeviceChooser(DeviceChooserDialog.java:69)
	at com.developerphil.adbidea.ui.DeviceChooserDialog.<init>(DeviceChooserDialog.java:46)
	at com.developerphil.adbidea.adb.AdbFacade.askUserForDevice(AdbFacade.java:119)
	at com.developerphil.adbidea.adb.AdbFacade.getDevice(AdbFacade.java:91)
	at com.developerphil.adbidea.adb.AdbFacade.executeOnDevice(AdbFacade.java:51)
	at com.developerphil.adbidea.adb.AdbFacade.uninstall(AdbFacade.java:27)
	at com.developerphil.adbidea.action.UninstallAction.actionPerformed(UninstallAction.java:10)
	at com.developerphil.adbidea.action.AdbAction.actionPerformed(AdbAction.java:13)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFactoryImpl.java:746)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: java.lang.NoSuchMethodException: org.jetbrains.android.run.DeviceChooser.<init>(java.lang.Boolean, com.intellij.openapi.ui.DialogWrapper$OkAction, org.jetbrains.android.facet.AndroidFacet, com.developerphil.adbidea.ui.DeviceChooserDialog$2)
	at java.lang.Class.getConstructor0(Class.java:2763)
	at java.lang.Class.getConstructor(Class.java:1693)
	at org.joor.Reflect.create(Reflect.java:409)
	... 27 more

**Comment by pbreault** [comment]
Hi @xgear-public ,

Thanks for reporting it. 
I am nearly finished with this bug, I will push a new version during the weekend.

**Comment by xgear-public** [comment]
Thank you for great plugin! Very useful!

**Comment by pbreault** [comment]
hi @xgear-public, this is now fixed in 1.2.2
You can update the plugin and everything should be fine!
