### ISSUE TITLE
Device chooser is broken on AS 1.5 RC1

### ISSUE THREAD

**Issue by IronBlossom** [pbreault/adb-idea#29]
When more than one device Device Chooser doesn't show up any. IDE throws internal error:

**com.android.tools.idea.run.LaunchCompatibility.canRunOnDevice(Lcom/android/sdklib/AndroidVersion;Lcom/android/sdklib/IAndroidTarget;Ljava/util/EnumSet;Lcom/android/ddmlib/IDevice;Lcom/android/sdklib/IAndroidTarget;)Lcom/android/tools/idea/run/LaunchCompatibility;
java.lang.NoSuchMethodError: com.android.tools.idea.run.LaunchCompatibility.canRunOnDevice(Lcom/android/sdklib/AndroidVersion;Lcom/android/sdklib/IAndroidTarget;Ljava/util/EnumSet;Lcom/android/ddmlib/IDevice;Lcom/android/sdklib/IAndroidTarget;)Lcom/android/tools/idea/run/LaunchCompatibility;
	at com.developerphil.adbidea.ui.MyDeviceChooser$MyDeviceTableModel.getValueAt(MyDeviceChooser.java:421)
	at javax.swing.JTable.getValueAt(JTable.java:2717)
	at com.intellij.ui.table.JBTable.getRowHeight(JBTable.java:139)
	at javax.swing.JTable.getRowHeight(JTable.java:994)
	at javax.swing.JTable.getCellRect(JTable.java:2937)
	at javax.swing.JTable.valueChanged(JTable.java:4698)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:164)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:211)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:405)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:415)
	at javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:459)
	at com.developerphil.adbidea.ui.MyDeviceChooser.refreshTable(MyDeviceChooser.java:295)
	at com.developerphil.adbidea.ui.MyDeviceChooser.access$600(MyDeviceChooser.java:67)
	at com.developerphil.adbidea.ui.MyDeviceChooser$6.run(MyDeviceChooser.java:274)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:154)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:182)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:221)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:219)
	at java.awt.Dialog.show(Dialog.java:1082)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:778)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:465)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1614)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1571)
	at com.developerphil.adbidea.adb.AdbFacade.askUserForDevice(AdbFacade.java:120)
	at com.developerphil.adbidea.adb.AdbFacade.getDevice(AdbFacade.java:91)
	at com.developerphil.adbidea.adb.AdbFacade.executeOnDevice(AdbFacade.java:51)
	at com.developerphil.adbidea.adb.AdbFacade.clearDataAndRestart(AdbFacade.java:47)
	at com.developerphil.adbidea.action.ClearDataAndRestartAction.actionPerformed(ClearDataAndRestartAction.java:10)
	at com.developerphil.adbidea.action.AdbAction.actionPerformed(AdbAction.java:13)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFactoryImpl.java:746)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)**

The change notes say **NoSuchMethodError** is fixed on 1.2.3 build. And It actually did, but on 1.5 _Beta_. After upgrading to _RC1_ its broke again
![capture](https://cloud.githubusercontent.com/assets/1793179/11113107/1466c8da-8944-11e5-90ca-4952dc135625.PNG)

**Comment by xgear-public** [comment]
issue occurred on AS 1.5 release

**Comment by IronBlossom** [comment]
Yes, Just updated to 1.5 from RC1. Its still not fixed.

**Comment by pbreault** [comment]
Hi @xgear-public / @IronBlossom.
This is fixed in 1.2.4.
Thanks,

**Comment by xgear-public** [comment]
Thank you a lot!
