### ISSUE TITLE
Plugin actions don't work if multiple devices are connected

### ISSUE THREAD

**Issue by zharf** [pbreault/adb-idea#73]
Having multiple devices connected and running some action causes this exception
```
com.android.tools.idea.model.AndroidModuleInfo.getInstance(Lorg/jetbrains/android/facet/AndroidFacet;)Lcom/android/tools/idea/model/AndroidModuleInfo;
java.lang.NoSuchMethodError: com.android.tools.idea.model.AndroidModuleInfo.getInstance(Lorg/jetbrains/android/facet/AndroidFacet;)Lcom/android/tools/idea/model/AndroidModuleInfo;
	at com.developerphil.adbidea.ui.MyDeviceChooser.<init>(MyDeviceChooser.java:115)
	at com.developerphil.adbidea.ui.DeviceChooserDialog.<init>(DeviceChooserDialog.java:40)
	at com.developerphil.adbidea.adb.DeviceResultFetcher.showDeviceChooserDialog(DeviceResultFetcher.kt:71)
	at com.developerphil.adbidea.adb.DeviceResultFetcher.fetch(DeviceResultFetcher.kt:36)
	at com.developerphil.adbidea.adb.AdbFacade.executeOnDevice(AdbFacade.java:53)
	at com.developerphil.adbidea.adb.AdbFacade.restartDefaultActivity(AdbFacade.java:35)
	at com.developerphil.adbidea.action.RestartAction.actionPerformed(RestartAction.java:10)
	at com.developerphil.adbidea.action.AdbAction.actionPerformed(AdbAction.java:13)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:216)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:233)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:968)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:958)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.lambda$onChosen$0(PopupFactoryImpl.java:952)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:193)
	at com.intellij.ui.popup.AbstractPopup.lambda$null$8(AbstractPopup.java:1428)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

My guess is that some version of IDEA broke something as there used to be a device selector in this case...

**Comment by zharf** [comment]
This seems to be fixed in the latest version with IDEA 181.2784.17
